### PR TITLE
[WIP] New styles for Decidim Docs

### PR DESCRIPTION
**Pull request by martuishere**
[WIP, it requires some fixes before merging]

New styles for Decidim Docs, header, navigation and landing.

Changes required before merging:

- Change landing h1 to "decidim docs" in content repo
- Header sliding navigation should display the proper navigation (this should be done in content repo?)

### CODE REVIEW

**Comment by martuishere** [comment]
@gmarpons This is almost ready for merging. Could you take a look at the two content issues (landing title and navigation)?

**Comment by martuishere** [comment]
@gmarpons For clarification, I'm attaching the expected styles in home, right-sliding navigation and navigation inside a "guide".

I think the fixes left are the home title (I'd call it "decidim docs") and the right-sliding navigation. Should the navigation be changed in the content repo (docs.decidim.org) or in the ui repo? Could you please take a look and do the necessary fixes?

Screenshot 2019-04-24 at 09 48 46
Screenshot 2019-04-24 at 09 48 59
Screenshot 2019-04-24 at 09 49 28

**Comment by gmarpons** [comment]
> I think the fixes left are the home title (I'd call it "decidim docs") 

Agree.

> and the right-sliding navigation. Should the navigation be changed in the content repo (docs.decidim.org) or in the ui repo?

We have to decide what items to include in the menu. If they are static, they can be defined in the ui repo.

**Comment by gmarpons** [comment]
For me we can merge this because it's not going to be in production until the site is re-deployed.

Two things I didn't notice yesterday:

1. The language selector is going to be in the main bar or can be integrated in the drop-down menu?

2. We need an "Edit on GitHub" button.

**Comment by htmlboy** [comment]
@gmarpons 
> We have to decide what items to include in the menu. If they are static, they can be defined in the ui repo.

Shouldn't be the links we already have in the home page, so they're accessible everywhere? (Project & community links and Software manuals) It makes sense to build them from the content repo, I guess.

> The language selector is going to be in the main bar or can be integrated in the drop-down menu?

It could be in both places. We added it to the main bar following the decidim.org pattern. Thoughts?

> We need an "Edit on GitHub" button.

My fault, I thought we didn't want to display it since casual contributing would be rare. Should it be everywhere but the home page, then?

**Comment by gmarpons** [comment]
> > The language selector is going to be in the main bar or can be integrated in the drop-down menu?
> 
> It could be in both places. We added it to the main bar following the decidim.org pattern. Thoughts?

You're right, I didn't see it in the main paige at decidim.org and thought it was only in the menu. Yes, we can follow the same pattern used for decidim.org.

**Comment by gmarpons** [comment]
> > We have to decide what items to include in the menu. If they are static, they can be defined in the ui repo.
> 
> Shouldn't be the links we already have in the home page, so they're accessible everywhere? (Project & community links and Software manuals) It makes sense to build them from the content repo, I guess.

I have to think about it. Some items can be static and some can be generated from contents repo. You can merge this, anyway.

**Comment by htmlboy** [comment]
@gmarpons ok, what about this?

>  We need an "Edit on GitHub" button.

> My fault, I thought we didn't want to display it since casual contributing would be rare. Should it be everywhere but the home page, then?

**Comment by xabier** [comment]
hi folks, is there a functional description of the requirements for this improvements? I don't want to re-invent the wheel or step ignoring previous work, but I had some ideas. As the co-author of most of the documents on docs.decidim.org I had some concerns about how they are displayed.

**Comment by gmarpons** [comment]
> @gmarpons ok, what about this?
> 
> > We need an "Edit on GitHub" button.
> 
> > My fault, I thought we didn't want to display it since casual contributing would be rare. Should it be everywhere but the home page, then?

Yes, exactly. We don't need to mention GitHub: "Edit this page".

**Comment by gmarpons** [comment]
@xabier 

You can attach your requirements here or we can have a video call next week, whatever you prefer.

**Comment by martuishere** [comment]
> Yes, exactly. We don't need to mention GitHub: "Edit this page".

@gmarpons I just added the edit link to the toolbar.

**Comment by xabier** [comment]
Sorry I missed your responses. In case it helps, here are my suggestions:

1. Is it possible to add automatic numbering to the sections and subsections? it helps navigation and structuring the index as well.
2. Sub-sections are desirable to be navigated on the left-side menu. 
3. I suggest "Document information" to be the first page to be displayed, including the index within text below the title. 
4. Can we skip the non-capital letter? it looks weird on section and document titles.

**Comment by gmarpons** [comment]
@xabier:
 
>     1. Is it possible to add automatic numbering to the sections and subsections? it helps navigation and structuring the index as well.

I've always wanted section numbering, but it's not easy to combine automatic numbering with reusable contents, given that every major section has its own page. I open an issue to think how to implement this.

>     2. Sub-sections are desirable to be navigated on the left-side menu.

I also want this and this time I know how to implement it.
 
>     3. I suggest "Document information" to be the first page to be displayed, including the index within text below the title.

I think we need two templates, one for long, multi-page docs, that could work as you suggest, and one for short docs. In a short doc (e.g. Social Contract) I'd like to go to the contents directly, without an "information page" step.
 
>     4. Can we skip the non-capital letter? it looks weird on section and document titles.

I don't have an opinion on that one.

**Comment by xabier** [comment]
@gmarpons thanks for your feedback, i agree with your suggestions. I am worried about the white paper as a 

Regarding point **1**: Section numbering can be done by hand, maybe it is not a priority right now. Nice to hear about point **2** been doable. I agree with you on point **3**, my suggestion is that, while hte two templates are implemented the standard template be the long-text one, because we have more long documents than short ones. Regarding point **4** my simple question: is this (low letter titles) something we enforce by CSS or some kind of script?

I forgot to mention a 5th very important point:

5. Do we have in mind a button with PDF downloads? even for relatively short documents many people prefer to print or read on tablet and PDF format. I know automatic generation of a PDF

**Comment by htmlboy** [comment]
> 4. Can we skip the non-capital letter? it looks weird on section and document titles.

>  Regarding point 4 my simple question: is this (low letter titles) something we enforce by CSS or some kind of script?

It's enforced by CSS to keep consistency with [decidim.org](htttp://decidim.org). It could be easily reversed, but this was part of the brand's key design elements, and Decidim board asked to keep it that way.

**Comment by xabier** [comment]
Thanks @htmlboy for the explanation. while I was on the Decidim board this un-capitalization was explicitly declared as childish, immature and ridiculous, a well known design failure that other projects that previously "tried" it have reversed with time. But it is not on my hands to take that decision anymore.  Thanks again for the explanation

**Comment by htmlboy** [comment]
@xabier I see your point, but I think it's also important to keep the design consistency. If the board decides to changes this, it won't be a problem in docs, but I'd leave decidim.org as it is now, since it would require to adjust the whole interface.

**Comment by xabier** [comment]
sure @htmlboy I am not saying we should change that against the board decision. I just wanted to clarify, for the record, and also to know if the style is reversible (as is the case with CSS).

Points 2,3 and 5 are, IMO, the most important to clarify. For the rest, good work!

Also, there is a final section of the main docs.decidim.org page (screenshot attached). This section is very important because there is a lot of documentation that is not created with Github and needs to be listed there. I haven't updated that list, but it is quite extense, could you thinkg on how to include an index for it?
image

**Comment by andreslucena** [comment]
Hi all. 
I agree with @htmlboy - for consistency we should let the lowercase as it is and we can discuss it on another sprint. 
@xabier if you have more documents please send them 
Let's try to close this PR ASAP please.

**Comment by gmarpons** [comment]
@xabier Point 5: we have a quite solid (and tested in another project) solution for automatic PDF generation. I haven't had the time to deploy it, yet.

**Comment by xabier** [comment]
@andreslucena I have more documents, most of them are listed here:
https://www.zotero.org/groups/1607464/metadecidim/items/collectionKey/DWR7CKGM

I can export it to the desired format, but the list needs work, cleaning and organizing, there is people actually getting paid for doing this job, I cannot but collect the relevant document. I currently don't have the time to do the intensive work :-/

For the rest I never meant to reverse the lower-letter policy on this PR, I agree with @htmlboy

**Pull request merged**
